export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SET_IS_ARTIST = 'SET_IS_ARTIST';
export const SET_IS_CONSUMER = 'SET_IS_CONSUMER';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const ONE_SIGNAL_ID = 'ONE_SIGNAL_ID';
export const PROFILE_UPDATE = 'PROFILE_UPDATE';
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS';
export const SEND_OTP_FAIL = 'SEND_OTP_FAIL';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAIL = 'VERIFY_OTP_FAIL';
export const SAVE_USER_DATA = 'SAVE_USER_DATA';
export const SAVE_TOKEN = 'SAVE_TOKEN';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_DATA = 'GET_CATEGORIES_DATA';

export const PUBLISH_GIG = 'PUBLISH_GIG';
export const PUBLISH_GIG_SUCCESS = 'PUBLISH_GIG_SUCCESS';
export const PUBLISH_GIG_ERROR = 'PUBLISH_GIG_ERROR';

export const GET_CERTIFICATES_DATA = 'GET_CERTIFICATES_DATA';
export const GET_EXPERIENCE_DATA = 'GET_EXPERIENCE_DATA';

export const GET_SERVICES = 'GET_SERVICES';
export const GET_SERVICES_DATA = 'GET_SERVICES_DATA';
export const GET_SERVICES_ERROR = 'GET_SERVICES_ERROR';
export const GET_PORTFOLIO_ERROR = 'GET_PORTFOLIO_ERROR';
export const GET_PORTFOLIO_DATA = 'GET_PORTFOLIO_DATA';

export const GIG = 'GIG';
export const GET_GIGS_SUCCESS = 'GET_GIGS_SUCCESS';
export const GET_GIGS_ERROR = 'GET_GIGS_ERROR';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_MY_PROFILE = 'GET_MY_PROFILE';
export const GET_USER_DETAIL = 'GET_USER_DETAIL';
export const GET_AVAILABLE_DAYS = 'GET_AVAILABLE_DAYS';
export const GET_BOOKING_SLOTS = 'GET_BOOKING_SLOTS';

export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDERS_DATA = 'GET_ORDERS_DATA';
export const GET_ORDERS_ERROR = 'GET_ORDERS_ERROR';
export const GET_CURRENT_LOCATION = 'GET_CURRENT_LOCATION';

export const GET_DISCOVERIES = 'GET_DISCOVERIES';
export const GET_DISCOVERIES_DATA = 'GET_DISCOVERIES_DATA';
export const GET_DISCOVERIES_ERROR = 'GET_DISCOVERIES_ERROR';

export const GET_CONSUMER_BROWSE = 'GET_CONSUMER_BROWSE';
export const GET_CONSUMER_BROWSE_DATA = 'GET_CONSUMER_BROWSE_DATA';
export const GET_CONSUMER_BROWSE_ERROR = 'GET_CONSUMER_BROWSE_ERROR';

export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_CART_LOADING = 'ADD_TO_CART_LOADING';
export const ADD_TO_CART_ERROR = 'ADD_TO_CART_ERROR';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const GET_CART_ITEM = 'GET_CART_ITEM';
export const GET_CART_ITEM_LOADING = 'GET_CART_ITEM_LOADING';
export const GET_CART_ITEM_ERROR = 'GET_CART_ITEM_ERROR';
