export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SET_IS_ARTIST = 'SET_IS_ARTIST';
export const SET_IS_CONSUMER = 'SET_IS_CONSUMER';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const ONE_SIGNAL_ID = 'ONE_SIGNAL_ID';
export const PROFILE_UPDATE = 'PROFILE_UPDATE';
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS';
export const SEND_OTP_FAIL = 'SEND_OTP_FAIL';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAIL = 'VERIFY_OTP_FAIL';
export const SAVE_USER_DATA = 'SAVE_USER_DATA';
export const SAVE_TOKEN = 'SAVE_TOKEN';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_DATA = 'GET_CATEGORIES_DATA';

export const PUBLISH_GIG = 'PUBLISH_GIG';
export const PUBLISH_GIG_SUCCESS = 'PUBLISH_GIG_SUCCESS';
export const PUBLISH_GIG_ERROR = 'PUBLISH_GIG_ERROR';

export const GET_CERTIFICATES_DATA = 'GET_CERTIFICATES_DATA';
export const GET_EXPERIENCE_DATA = 'GET_EXPERIENCE_DATA';

export const GET_SERVICES = 'GET_SERVICES';
export const GET_SERVICES_DATA = 'GET_SERVICES_DATA';
export const GET_SERVICES_ERROR = 'GET_SERVICES_ERROR';
